### ISSUE TITLE
Error of installing on local

### ISSUE THREAD

**Issue by hxuanhung** [containership/containership.cli#38]
Hi, I try to install it on local with `npm install containership.cli -g` and I get this error: 
```
npm WARN npm@2.2.0 had bundled packages that do not match the required version(s). They have been replaced with non-bundled versions.

npm ERR! path /home/hxhung/.nvm/versions/node/v8.0.0/lib/node_modules/chownr/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -2
npm ERR! syscall open
npm ERR! package.json ENOENT: no such file or directory, open '/home/hxhung/.nvm/versions/node/v8.0.0/lib/node_modules/chownr/package.json'
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hxhung/.npm/_logs/2017-09-14T08_31_56_227Z-debug.log
```
I'm using node v8.0.0

**Comment by nicktate** [comment]
@hxuanhung Version 2.0 of the `containership.cli` will be published and released today. It has not yet been officially released, and the version in npm is an old `1.x` version that I can't guarantee will work with node `8.x`. 

I will comment and close this issue later today once the `2.x` version is published to NPM.

**Comment by nicktate** [comment]
@hxuanhung CLI V2 has been officially released. See https://containership.github.io/containership.cli/docs/installation/ for instructions on how to install. Let me know if you have any other questions.
